chore(global): general reorganization hellscape
Also in this commit:
* move source files to src directory
* lock image tag on per-version basis
* use Doppler to authenticate against quay.io and dock.mau.dev in build CI

diff --git a/src/usr/bin/vaultwarden-startup b/src/usr/bin/vaultwarden-startup
--- a/src/usr/bin/vaultwarden-startup
+++ b/src/usr/bin/vaultwarden-startup
@@ -6,11 +6,6 @@ if [[ "${MAKE_IT_FAIL}" == "true" ]]; then
    echo "error: either set it to 'false' or just remove it entirely on your SaaS provider's"
    echo "error: env vars settings page. Exiting..."
    exit
-elif [[ "${MAKE_IT_FAIL}" == "false" ]]; then
-    echo "==> Looks fine, starting up..."
-else
-    echo "==> MAKE_IT_FAIL var contains unsupported options, starting up..."
-    echo "    Only true or false are supported. Leaving it blank is also fine."
 fi
 sleep 2
 
@@ -27,13 +22,10 @@ export DISABLE_ICON_DOWNLOAD=false
 export ICON_CACHE_TTL=120
 export ICON_CACHE_NEGTTL=0
 
-# Checks for different providers to provide customized error messages and some fixes.
-if [[ -n "$RAILWAY_STATIC_URL" ]]; then
-  export DEPLOY_METHOD="railway"
-  export IP_HEADER=X-Forwarded-For
-elif [[ -n "$SSO_DSN" ]] || [[ -n "$DOMAIN_ALIASES" ]]; then
-  export DEPLOY_METHOD="divio"
-  export IP_HEADER=X-Forwarded-For
+if [[ $CF_PROXY == true ]]; then
+  export IP_HEADER=CF-Connecting-IP
+else
+  export IP_HEADER=${IP_HEADER:-"X-Forwarded-For"}
 fi
 
 if [[ "${ENABLE_ADMIN}" == "true" ]]; then
@@ -71,6 +63,14 @@ sleep 3
 if [[ -z "${DATABASE_URL}" ]]; then
   echo "error: DATABASE_URL is undefined, thus the server will not start. To continue, add an DATABASE_URL secret on your PaaS service."
   echo "error: If you're running locally,  ease setup an Postgres instance"
+  exit 1
+fi
+
+if [[ "${I_REALLY_WANT_VOLATILE_STORAGE}" == "true" ]]; then
+  true
+elif [[ "${I_REALLY_WANT_VOLATILE_STORAGE}" != "true" ]] && [[ "${SAFETY_LOCK_DATADIR}" == "$(cat /etc/safety-lock/datadir/code.txt)" ]]; then
+  echo "error: To avoid data loss, either setup an container volume for the data directory or"
+  echo "error: set I_REALLY_WANT_VOLATILE_STORAGE to true, assuming you know what you're doing."
   exit 1
 fi
 
